### ISSUE TITLE
使用源码生成的可执行文件不可使用，下载编译好的包也是不可使用

### ISSUE THREAD

**Issue by dadingjianhui** [jingsam/foxgis-server-lite#158]
root:# ./foxgis-server-lite-linux 
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, read
    at error_EISDIR (pkg/prelude/bootstrap.js:553:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:894:33)
    at Object.readFileSync (pkg/prelude/bootstrap.js:938:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/snapshot/foxgis-server-lite/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1686:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)

这是下载好的可执行文件 直接使用 也是不行，我的需求是要安装到arm架构的所以是使用源码编译的，编译成功后不可使用，我一度怀疑是我自己的问题，后来下载了这个直接使用的编译好的文件，也是不可使用，想问问作者大大，能不能帮忙解决一下呢

**Comment by jingsam** [comment]
arm版本得自己从代码编译哦，pkg的targets改为arm64

**Comment by pantt** [comment]
> arm64



> arm版本得自己从代码编译哦，pkg的targets改为arm64
大佬求问，我也是同样问题 ，需要arm架构的，targets改了，报错，是不是命令不对呀？
 "dist": "pkg . --out-path=dist/ --targets=arm64 --compress=GZip"

![image](https://github.com/jingsam/foxgis-server-lite/assets/44255498/35248675-916a-4012-b417-84c6f3163d88)

**Comment by jingsam** [comment]
用macos-arm64试试

**Comment by pantt** [comment]
> macos-arm64
大佬谢谢回复，用macos-arm64是这样的，我试了下用同事的windows电脑，用的--targets=arm64也是这个报错spawn Unknown(哭)

![image](https://github.com/jingsam/foxgis-server-lite/assets/44255498/a4b79393-41ae-4780-837e-2f735983353e)

**Comment by pantt** [comment]
> 用macos-arm64试试

大佬，求求了，出一个arm的部署包吧，或者script里面加一个能打包出arm的命令，救救孩子吧

**Comment by pantt** [comment]
> 用macos-arm64试试

大佬我弄好了，原来是需要在arm机器上进行打包才能成功。

**Comment by leishenglong** [comment]
@pantt 在arm机器上离线打包吗，大佬能把你打包好的的arm的包共享下吗？感谢
