### ISSUE TITLE
yarn命令执行失败?

### ISSUE THREAD

**Issue by tisttsf** [jingsam/foxgis-server-lite#93]
我在两台机器上都克隆了完整仓库
安装了 yarn
然后尝试执行yarn命令
win10系统显示

> gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | win32 | x64
gyp info find Python using Python version 3.9.0 found at "C:\Python39\python.exe"
gyp http GET https://nodejs.org/download/release/v14.15.1/node-v14.15.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "W:\\xx_zd\\node\\node.exe" "W:\\xx_zd\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=W:\\cl\\foxgis-server-lite\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=W:\\cl\\foxgis-server-lite\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd W:\cl\foxgis-server-lite\node_modules\sqlite3
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=W:\cl\foxgis-server-lite\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=W:\cl\foxgis-server-lite\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (W:\cl\foxgis-server-lite\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "W:\\xx_zd\\node\\node.exe" "W:\\cl\\foxgis-server-lite\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd W:\cl\foxgis-server-lite\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=W:\cl\foxgis-server-lite\node_module

ubuntu显示

> 00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'test'

请问应该怎么做?

**Comment by jingsam** [comment]
node_sqlite3.node这个二进制扩展是放到aws上的，得翻墙才能下载，另外文档中有打包好的安装包。

**Comment by tisttsf** [comment]
> node_sqlite3.node这个二进制扩展是放到aws上的，得翻墙才能下载，另外文档中有打包好的安装包。

我是用安装好的安装包,在命令行运行好像也没效果

![for目录_1](https://user-images.githubusercontent.com/4705133/110628562-1cc00080-81de-11eb-91cd-0a18454cd98a.PNG)
这里应该怎么做 直接在命令行输入 foxgis-server-lite-win.exe吗?我输入直接没反应结束,也没法打开`http://localhost:1234/api
`

**Comment by jingsam** [comment]
切换到当前目录下，命令行执行foxgis-server-lite-win, 看到Listening on 1234就表示启动了

**Comment by jingsam** [comment]
在cmd里面执行试试

**Comment by tisttsf** [comment]
> 在cmd里面执行试试

刚试了,一样的反应啊

**Comment by xupeng-faker** [comment]
也是 exe 执行毫无反应

**Comment by jingsam** [comment]
我已经重新更新了一个版本，请重新下载试试
